language: node_js
node_js:
  - "8"
cache: npm
git:
  depth: 3
notifications:
  email: false
script:
  - commitlint-travis
  - npm run lint
  - npm test
after_success:
  - npm run test:coverage
  - bash <(curl -s https://codecov.io/bash)
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && npm run semantic-release
